name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          # Updated dependencies for Ubuntu 24.04 (Removed libtinfo5, changed to libncurses-dev)
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          
          # Added --break-system-packages to bypass Ubuntu 24.04 pip restriction
          pip3 install --user --upgrade buildozer cython virtualenv --break-system-packages

      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: bin/*.apk

